name = "seo-sci-dev"
compatibility_date = "2024-09-03"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".vercel/output/static"

[placement]
mode = "smart"

[[d1_databases]]
binding = "DATABASE"
database_name = "seo-sci-ai-dev-db"
database_id = "d3d93d42-23b8-4adb-8753-13577e8034fc"
migrations_dir = "./drizzle"

# Queue bindings
[[queues.producers]]
binding = "QUEUE_BINDING"
queue = "site-audit"
